## static_countries
UPDATE static_countries SET cn_short_zh='安道尔' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_zh='阿拉伯联合酋长国' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_zh='阿富汗' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_zh='安提瓜和巴布达' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_zh='安圭拉' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_zh='阿尔巴尼亚' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_zh='亚美尼亚' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_zh='Niederländische Antillen' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_zh='安哥拉' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_zh='南极洲' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_zh='阿根廷' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_zh='萨摩亚' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_zh='奥地利' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_zh='澳大利亚' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_zh='阿鲁巴' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_zh='阿塞拜疆' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_zh='波斯尼亚 - 黑塞哥维那' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_zh='巴巴多斯' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_zh='孟加拉国' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_zh='比利时' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_zh='布基纳法索' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_zh='保加利亚' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_zh='巴林' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_zh='蒲隆地' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_zh='贝宁' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_zh='百慕达群岛' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_zh='文莱达鲁萨兰国' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_zh='玻利维亚' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_zh='巴西' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_zh='巴哈马' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_zh='不丹' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_zh='Bouvetinsel' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_zh='博茨瓦纳' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_zh='Weißrussland' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_zh='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_zh='加拿大' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_zh='Kokosinseln (Keeling)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_zh='刚果共和国' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_zh='中非共和国' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_zh='Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_zh='瑞士' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_zh='Elfenbeinküste' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_zh='Cookinseln' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_zh='智利' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_zh='喀麦隆' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_zh='中国' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_zh='哥伦比亚' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_zh='哥斯达黎加' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_zh='古巴' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_zh='佛得角' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_zh='Weihnachtsinsel' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_zh='塞浦路斯' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_zh='捷克共和国' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_zh='德国' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_zh='Dschibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_zh='丹麦' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_zh='多米尼克' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_zh='多米尼加共和国' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_zh='阿尔及利亚' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_zh='厄瓜多尔' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_zh='爱沙尼亚' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_zh='埃及' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_zh='Westsahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_zh='厄立特里亚' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_zh='西班牙' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_zh='埃塞俄比亚' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_zh='芬兰' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_zh='斐济' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_zh='Falklandinseln' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_zh='Mikronesien' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_zh='Färöer' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_zh='法国' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_zh='加蓬' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_zh='英国' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_zh='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_zh='格鲁吉亚' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_zh='Französisch-Guayana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_zh='加纳' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_zh='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_zh='格陵兰' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_zh='冈比亚' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_zh='几内亚' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_zh='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_zh='Äquatorialguinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_zh='希腊' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_zh='Südgeorgien und die Südlichen Sandwichinseln' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_zh='危地马拉' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_zh='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_zh='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_zh='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_zh='香港' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_zh='洪都拉斯' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_zh='克罗地亚' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_zh='海地' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_zh='匈牙利' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_zh='印度尼西亚' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_zh='爱尔兰' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_zh='以色列' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_zh='印度' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_zh='Britisches Territorium im Indischen Ozean' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_zh='伊拉克' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_zh='伊朗' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_zh='冰岛' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_zh='意大利' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_zh='牙买加' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_zh='约旦' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_zh='日本' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_zh='Kenia' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_zh='Kirgisistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_zh='柬埔寨' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_zh='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_zh='Komoren' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_zh='圣基茨和尼维斯' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_zh='Demokratische Volksrepublik Korea' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_zh='Republik Korea' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_zh='科威特' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_zh='Kaimaninseln' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_zh='哈萨克斯坦' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_zh='老挝' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_zh='黎巴嫩' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_zh='圣卢西亚' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_zh='列支敦士登' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_zh='斯里兰卡' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_zh='利比里亚' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_zh='莱索托' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_zh='Litauen' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_zh='卢森堡' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_zh='Lettland' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_zh='利比亚' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_zh='Marokko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_zh='摩纳哥' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_zh='Republik Moldau' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_zh='马达加斯加' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_zh='Marschallinseln' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_zh='Mazedonien' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_zh='马里' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_zh='缅甸' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_zh='Mongolei' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_zh='澳门' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_zh='Nördliche Marianen' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_zh='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_zh='Mauretanien' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_zh='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_zh='马耳他' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_zh='毛里求斯' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_zh='马尔代夫' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_zh='马拉维' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_zh='墨西哥' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_zh='马来西亚' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_zh='莫桑比克' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_zh='纳米比亚' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_zh='Neukaledonien' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_zh='尼日尔' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_zh='Norfolkinsel' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_zh='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_zh='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_zh='荷兰' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_zh='挪威' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_zh='尼泊尔' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_zh='瑙鲁' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_zh='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_zh='荷兰' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_zh='阿曼' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_zh='巴拿马' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_zh='秘鲁' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_zh='Französisch-Polynesien' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_zh='P巴布亚新几内亚' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_zh='菲律宾' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_zh='巴基斯坦' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_zh='波兰' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_zh='St. Pierre und Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_zh='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_zh='Puerto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_zh='葡萄牙' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_zh='帕劳' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_zh='巴拉圭' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_zh='卡塔尔' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_zh='Reunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_zh='罗马尼亚' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_zh='俄罗斯' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_zh='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_zh='沙特阿拉伯' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_zh='Salomonen' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_zh='Seychellen' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_zh='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_zh='瑞典' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_zh='新加坡' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_zh='St. Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_zh='Slowenien' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_zh='Svalbard und Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_zh='Slowakei' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_zh='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_zh='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_zh='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_zh='Somalia' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_zh='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_zh='São Tomé und Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_zh='萨尔瓦多' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_zh='叙利亚' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_zh='Swasiland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_zh='Turks- und Caicosinseln' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_zh='乍得' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_zh='Französische Süd- und Antarktisgebiete' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_zh='多哥' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_zh='泰国' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_zh='Tadschikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_zh='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_zh='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_zh='突尼斯' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_zh='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_zh='东帝汶' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_zh='土耳其' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_zh='特立尼达和多巴哥' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_zh='吐瓦鲁' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_zh='台湾' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_zh='Tansania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_zh='乌克兰' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_zh='乌干达' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_zh='Amerikanisch-Ozeanien' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_zh='Vereinigte Staaten von Amerika' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_zh='>乌拉圭' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_zh='乌兹别克斯坦' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_zh='梵帝冈' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_zh='St. Vinzent und die Grenadinen' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_zh='委内瑞拉' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_zh='Britische Jungferninseln' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_zh='Amerikanische Jungferninseln' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_zh='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_zh='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_zh='Wallis und Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_zh='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_zh='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_zh='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_zh='Südafrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_zh='赞比亚' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_zh='津巴布韦' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_zh='Palästina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_zh='Serbien und Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_zh='Alandinseln' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_zh='Heard und McDonaldinseln' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_zh='黑山' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_zh='塞尔维亚' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_zh='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_zh='Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_zh='Insel Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_zh='Saint-Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_zh='Saint-Barthélemy' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_zh='Bonaire, Sint Eustatius und Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_zh='Curaçao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_zh='Sint Maarten' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_zh='Südsudan' WHERE cn_iso_2='SS';